// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uieafhgmwnzczrozxsnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZWFmaGdtd256Y3pyb3p4c254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzY4NjMsImV4cCI6MjA2NzExMjg2M30.nV0A-Qognpj8nl7iV1aqP4YvCCnf6HfkxAYwOGpxnPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});